sonarqube-check:
  image: maven:3.6.3-jdk-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_HOST_URL: "http://sonar.eastbuy.com"
    #SONAR_TOKEN: "sqp_7491e577fcbcdd350b306344aa4a4080cddc5a5a"
    SONAR_LOGIN: "admin"
    SONAR_PASS: "dfzx,123"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn verify sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASS -Dsonar.projectKey=qa_changbai-mountain-testng_AYiPkBhzxekiqwuihFVb
    # - mvn clean verify sonar:sonar -Dsonar.projectKey=qa_changbai-mountain-testng_AYiPkBhzxekiqwuihFVb -Dsonar.host.url=https://sonar.eastbuy.com -Dsonar.login=sqp_51d3244cb226d339e39836a5606214d363f24888
  tags:
    - test